# ============================================
# BancoXYZ - Bank Backend
# ============================================

spring.application.name=bank-backend

server.port=8080

# ============================================
# PostgreSQL
# ============================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bancoxyz}
spring.datasource.username=${DB_USER:bancoxyz}
spring.datasource.password=${DB_PASSWORD:bancoxyz123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# JPA / Hibernate
# ============================================

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# ============================================
# Eureka Service Discovery
# ============================================

# Dirección del Discovery Server.
#
# Desarrollo local:
# http://127.0.0.1:8761/eureka/
#
# En AWS podrá reemplazarse mediante
# la variable de entorno EUREKA_SERVER_URL.
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://127.0.0.1:8761/eureka/}

# Bank Backend debe registrarse en Eureka
# y obtener el registro de los demás servicios.
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# ============================================
# Instancia Eureka
# ============================================

# Bank Backend actualmente trabaja mediante HTTP.
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false

eureka.instance.non-secure-port=${server.port}

# Durante desarrollo local utilizamos loopback.
# En AWS esta IP puede reemplazarse mediante
# EUREKA_INSTANCE_IP.
eureka.instance.prefer-ip-address=true
eureka.instance.ip-address=${EUREKA_INSTANCE_IP:127.0.0.1}

# Identificador claro dentro del dashboard Eureka.
eureka.instance.instance-id=${spring.application.name}:${server.port}

# URLs reales utilizadas por Eureka para
# representar el estado del servicio.
eureka.instance.status-page-url-path=/actuator/info
eureka.instance.health-check-url-path=/actuator/health

# ============================================
# Spring Boot Actuator
# ============================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always