# ============================================
# BancoXYZ - Eureka Discovery Server
# ============================================

spring.application.name=discovery-server

# Puerto estándar utilizado por Eureka Server.
server.port=8761

# ============================================
# Eureka Server
# ============================================

# Este módulo actúa únicamente como servidor
# de descubrimiento, por lo que no necesita
# registrarse a sí mismo como cliente.
eureka.client.register-with-eureka=false

# En una instalación standalone tampoco necesita
# descargar un registro desde otro Eureka Server.
eureka.client.fetch-registry=false

# Endpoint base utilizado posteriormente por
# los microservicios para registrarse.
eureka.client.service-url.defaultZone=http://127.0.0.1:8761/eureka/

# Host utilizado durante el desarrollo local.
eureka.instance.hostname=127.0.0.1

# ============================================
# Actuator
# ============================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always