--
-- PostgreSQL database dump
--

\restrict tWLBng7IvBR9u6bqy4uTZH6SW6lcT7v5ZBdfZDp2oqRIW0iymjCPpcvBUiHkVBB

-- Dumped from database version 17.11 (Debian 17.11-1.pgdg13+2)
-- Dumped by pg_dump version 17.11 (Debian 17.11-1.pgdg13+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cuentas_intereses; Type: TABLE; Schema: public; Owner: bancoxyz
--

CREATE TABLE public.cuentas_intereses (
    cuenta_id bigint NOT NULL,
    estado character varying(30) NOT NULL,
    interes_calculado numeric(19,2) NOT NULL,
    nombre character varying(100) NOT NULL,
    saldo_final numeric(19,2) NOT NULL,
    saldo_inicial numeric(19,2) NOT NULL,
    tasa_interes numeric(10,4) NOT NULL,
    tipo character varying(30) NOT NULL
);


ALTER TABLE public.cuentas_intereses OWNER TO bancoxyz;

--
-- Name: estados_cuenta_anuales; Type: TABLE; Schema: public; Owner: bancoxyz
--

CREATE TABLE public.estados_cuenta_anuales (
    id bigint NOT NULL,
    anio integer NOT NULL,
    cuenta_id bigint NOT NULL,
    saldo_anual numeric(19,2) NOT NULL,
    total_depositos numeric(19,2) NOT NULL,
    total_retiros numeric(19,2) NOT NULL,
    total_compras numeric(19,2) NOT NULL
);


ALTER TABLE public.estados_cuenta_anuales OWNER TO bancoxyz;

--
-- Name: estados_cuenta_anuales_id_seq; Type: SEQUENCE; Schema: public; Owner: bancoxyz
--

ALTER TABLE public.estados_cuenta_anuales ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.estados_cuenta_anuales_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transacciones_procesadas; Type: TABLE; Schema: public; Owner: bancoxyz
--

CREATE TABLE public.transacciones_procesadas (
    id bigint NOT NULL,
    estado character varying(30) NOT NULL,
    fecha date NOT NULL,
    monto numeric(19,2) NOT NULL,
    observacion character varying(255),
    tipo character varying(30) NOT NULL
);


ALTER TABLE public.transacciones_procesadas OWNER TO bancoxyz;

--
-- Data for Name: cuentas_intereses; Type: TABLE DATA; Schema: public; Owner: bancoxyz
--

COPY public.cuentas_intereses (cuenta_id, estado, interes_calculado, nombre, saldo_final, saldo_inicial, tasa_interes, tipo) FROM stdin;
\.


--
-- Data for Name: estados_cuenta_anuales; Type: TABLE DATA; Schema: public; Owner: bancoxyz
--

COPY public.estados_cuenta_anuales (id, anio, cuenta_id, saldo_anual, total_depositos, total_retiros, total_compras) FROM stdin;
\.


--
-- Data for Name: transacciones_procesadas; Type: TABLE DATA; Schema: public; Owner: bancoxyz
--

COPY public.transacciones_procesadas (id, estado, fecha, monto, observacion, tipo) FROM stdin;
\.


--
-- Name: estados_cuenta_anuales_id_seq; Type: SEQUENCE SET; Schema: public; Owner: bancoxyz
--

SELECT pg_catalog.setval('public.estados_cuenta_anuales_id_seq', 1, false);


--
-- Name: cuentas_intereses cuentas_intereses_pkey; Type: CONSTRAINT; Schema: public; Owner: bancoxyz
--

ALTER TABLE ONLY public.cuentas_intereses
    ADD CONSTRAINT cuentas_intereses_pkey PRIMARY KEY (cuenta_id);


--
-- Name: estados_cuenta_anuales estados_cuenta_anuales_pkey; Type: CONSTRAINT; Schema: public; Owner: bancoxyz
--

ALTER TABLE ONLY public.estados_cuenta_anuales
    ADD CONSTRAINT estados_cuenta_anuales_pkey PRIMARY KEY (id);


--
-- Name: transacciones_procesadas transacciones_procesadas_pkey; Type: CONSTRAINT; Schema: public; Owner: bancoxyz
--

ALTER TABLE ONLY public.transacciones_procesadas
    ADD CONSTRAINT transacciones_procesadas_pkey PRIMARY KEY (id);


--
-- Name: estados_cuenta_anuales uk_estado_cuenta_anio; Type: CONSTRAINT; Schema: public; Owner: bancoxyz
--

ALTER TABLE ONLY public.estados_cuenta_anuales
    ADD CONSTRAINT uk_estado_cuenta_anio UNIQUE (cuenta_id, anio);


--
-- PostgreSQL database dump complete
--

\unrestrict tWLBng7IvBR9u6bqy4uTZH6SW6lcT7v5ZBdfZDp2oqRIW0iymjCPpcvBUiHkVBB

