<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.bancoxyz</groupId>
    <artifactId>bancoxyzbatch</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <name>BancoXYZ - Semana 6</name>

    <description>
        Proyecto agregador Maven de BancoXYZ para la implementación
        de microservicios, configuración centralizada, Service Discovery,
        seguridad y tolerancia a fallos con Spring Cloud.
    </description>

    <modules>

        <!-- Infraestructura Spring Cloud -->
        <module>Semana 6/config-server</module>
        <module>Semana 6/discovery-server</module>

        <!-- API bancaria -->
        <module>Semana 6/bank-backend</module>

        <!-- Backend for Frontend -->
        <module>Semana 6/bff/bff-web</module>
        <module>Semana 6/bff/bff-mobile</module>
        <module>Semana 6/bff/bff-atm</module>

    </modules>

</project>