<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
             http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>cl.duoc.bancoxyz</groupId>
    <artifactId>bancoxyzbatch</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>BancoXYZ Batch - Semana 5</name>
    <description>
        Proyecto agregador Maven para Bank Backend y los tres Backend for Frontend.
    </description>

    <modules>
        <module>Semana 5/bank-backend</module>
        <module>Semana 5/bff/bff-web</module>
        <module>Semana 5/bff/bff-mobile</module>
        <module>Semana 5/bff/bff-atm</module>
    </modules>

</project>