# ============================================
# BancoXYZ - BFF Web
# ============================================

spring.application.name=bff-web

# ============================================
# Spring Cloud Config
# ============================================

# Config Server centralizado de BancoXYZ.
# Sin "optional:" para exigir que el servidor
# de configuración esté disponible al iniciar.
spring.config.import=configserver:
spring.cloud.config.uri=http://127.0.0.1:8888

# ============================================
# Servidor
# ============================================

server.port=8081

# ============================================
# HTTPS
# ============================================

server.ssl.enabled=true
server.ssl.key-store=classpath:certs/bff-web.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-web

# ============================================
# Seguridad
# ============================================

security.tokens.web=${WEB_API_TOKEN:bancoxyz-web-demo-token-2026}
security.tokens.mobile=${MOBILE_API_TOKEN:bancoxyz-mobile-demo-token-2026}
security.tokens.atm=${ATM_API_TOKEN:bancoxyz-atm-demo-token-2026}
