spring.application.name=bff-mobile
server.port=8082
backend.base-url=http://localhost:8080

spring.security.user.name=mobile
spring.security.user.password=mobile123
spring.security.user.roles=MOBILE