spring.application.name=bancoxyzbatch

# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/bancoxyz}
spring.datasource.username=${DB_USER:bancoxyz}
spring.datasource.password=${DB_PASSWORD:bancoxyz123}
spring.datasource.driver-class-name=org.postgresql.Driver

# Mantengo conexiones suficientes para los procesos concurrentes.
spring.datasource.hikari.maximum-pool-size=10


# ===============================
# Inicialización SQL
# ===============================

# Inicializo de forma controlada e idempotente las tablas internas
# requeridas por Spring Batch en PostgreSQL.
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema-spring-batch-postgresql.sql


# ===============================
# Spring Batch
# ===============================

# Evito la ejecución automática de todos los Jobs.
# ControlledJobRunner determina cuál proceso ejecutar.
spring.batch.job.enabled=false


# ===============================
# JPA / Hibernate
# ===============================

# Mantengo sincronizadas las tablas correspondientes
# al modelo de negocio.
spring.jpa.hibernate.ddl-auto=update

# Reduzco ruido SQL durante las ejecuciones y mediciones.
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false


# ===============================
# Escalamiento y rendimiento
# ===============================

# Configuración final seleccionada a partir de las pruebas
# comparativas de rendimiento realizadas en Semana 3.
#
# Benchmark de hilos con chunk-size=5:
# 1 hilo  -> 567.333 ms
# 2 hilos -> 635.414 ms
# 3 hilos -> 584.033 ms
# 4 hilos -> 566.483 ms
#
# Benchmark de chunks con 4 hilos:
# chunk=1  -> 598.638 ms
# chunk=2  -> 644.882 ms
# chunk=5  -> 1073.013 ms
# chunk=10 -> 565.356 ms
#
# Mejor configuración observada en el escenario evaluado:
# 4 hilos y chunk de 10 registros.

app.batch.threads=4
app.batch.queue-capacity=20
app.batch.chunk-size=10


# ===============================
# Resiliencia
# ===============================

# Cantidad máxima de reintentos ante fallos transitorios.
app.batch.retry-max-retries=3

# Tiempo de espera entre reintentos, expresado en milisegundos.
app.batch.retry-delay-ms=500


# ===============================
# Prueba controlada de retry
# ===============================

# Permite simular fallos transitorios para validar
# experimentalmente la política de reintentos.
#
# Durante la ejecución normal debe permanecer en 0.
# La evidencia de Semana 3 utilizó temporalmente el valor 1
# para provocar un fallo controlado y comprobar la recuperación.
app.batch.retry-demo-failures=0
