# ============================================
# BancoXYZ - BFF Mobile
# ============================================

spring.application.name=bff-mobile

# ============================================
# Spring Cloud Config
# ============================================

# Configuración centralizada obtenida desde Config Server.
#
# Al no utilizar "optional:", BFF Mobile exige que
# Config Server esté disponible durante su arranque.
spring.config.import=configserver:
spring.cloud.config.uri=http://127.0.0.1:8888

# ============================================
# Servidor
# ============================================

server.port=8082

# ============================================
# HTTPS
# ============================================

# Certificado autofirmado utilizado para
# la demostración académica local.
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/bff-mobile.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-mobile

# ============================================
# Seguridad
# ============================================

# Los tres BFF conocen los tokens académicos para
# distinguir autenticación (401) de autorización (403).
#
# En producción estos secretos deberán reemplazarse
# por credenciales de corta duración emitidas por
# un proveedor de identidad.
security.tokens.web=${WEB_API_TOKEN:bancoxyz-web-demo-token-2026}
security.tokens.mobile=${MOBILE_API_TOKEN:bancoxyz-mobile-demo-token-2026}
security.tokens.atm=${ATM_API_TOKEN:bancoxyz-atm-demo-token-2026}