# ============================================
# BancoXYZ - Spring Cloud Config Server
# ============================================

spring.application.name=config-server

# Puerto convencional utilizado por Config Server.
server.port=8888

# ============================================
# Repositorio de configuraciones
# ============================================

# Durante desarrollo utilizaremos un repositorio local.
# Más adelante podrá reemplazarse por Git al desplegar
# la arquitectura en AWS.
spring.profiles.active=native

spring.cloud.config.server.native.search-locations=${CONFIG_REPO_PATH:file:../config-repo}

# Si una aplicación solicitada no existe en el repositorio,
# se devuelve error en lugar de una configuración vacía.
spring.cloud.config.server.accept-empty=false

# ============================================
# Actuator
# ============================================

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ============================================
# Health Check del Config Server
# ============================================

# El Health Indicator comprobará una configuración
# que realmente existe en nuestro repositorio.
spring.cloud.config.server.health.repositories.bffweb.name=bff-web
spring.cloud.config.server.health.repositories.bffweb.profiles=default