# ============================================
# BancoXYZ - BFF Mobile
# ============================================

spring.application.name=bff-mobile

# ============================================
# Spring Cloud Config
# ============================================

# Configuración centralizada obtenida desde Config Server.
#
# Al no utilizar "optional:", BFF Mobile exige que
# Config Server esté disponible durante su arranque.
spring.config.import=configserver:
spring.cloud.config.uri=http://127.0.0.1:8888

# ============================================
# Servidor
# ============================================

server.port=8082

# ============================================
# HTTPS
# ============================================

# Certificado autofirmado utilizado para
# la demostración académica local.
server.ssl.enabled=true
server.ssl.key-store=classpath:certs/bff-mobile.p12
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-mobile

# ============================================
# Seguridad
# ============================================

# OAuth2 Resource Server (JWT).
# El issuer público permanece estable para validar el claim "iss".
# La URL de JWK se puede resolver por la red interna de Docker.
spring.security.oauth2.resourceserver.jwt.issuer-uri=${OAUTH2_ISSUER_URI:http://localhost:8084/realms/bancoxyz}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${OAUTH2_JWK_SET_URI:http://localhost:8084/realms/bancoxyz/protocol/openid-connect/certs}
